"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
type Step=0|1|2|3|4|5; type Answers=Record<string,string>;
const steps=["Início","Conversa","Empresa","Diagnóstico","Entregáveis","Plano"];
const questions=[
 {id:"name",q:"Como você quer que eu te chame?",hint:"Seu primeiro nome já está ótimo."},
 {id:"company",q:"Qual é o nome da sua empresa?",hint:"Use o nome que seus clientes conhecem."},
 {id:"segment",q:"Em qual mercado sua empresa atua?",hint:"Ex.: construção, saúde, beleza, alimentação, serviços B2B."},
 {id:"offer",q:"O que sua empresa vende hoje?",hint:"Explique do seu jeito. Produtos, serviços ou os dois."},
 {id:"client",q:"Quem mais se beneficia do que vocês entregam?",hint:"Descreva o cliente que tem mais chance de comprar e ficar satisfeito."},
 {id:"problem",q:"Qual problema importante vocês resolvem para esse cliente?",hint:"Pense no que muda depois que ele compra."},
 {id:"difference",q:"Por que alguém deveria escolher vocês e não outra opção?",hint:"Pode ser atendimento, método, velocidade, segurança, especialização ou experiência."},
 {id:"acquisition",q:"Como os clientes chegam até a empresa hoje?",hint:"Indicação, Instagram, Google, tráfego, equipe comercial, parceiros…"},
 {id:"sales",q:"O que acontece entre o primeiro contato e a venda?",hint:"Conte o processo atual, mesmo que ele ainda seja informal."},
 {id:"bottleneck",q:"O que mais trava o crescimento neste momento?",hint:"Falta de demanda, posicionamento, vendas, equipe, operação, dados ou tecnologia."},
 {id:"goal",q:"Qual resultado seria realmente importante nos próximos 12 meses?",hint:"Diga o resultado e, se souber, uma meta concreta."},
 {id:"readiness",q:"Qual frente precisa de atenção primeiro?",hint:"Escolha a que mais representa o momento atual.",options:["Atrair mais clientes","Converter melhor","Organizar a operação","Usar melhor dados e tecnologia"]}
];
const esc=(v:string)=>v?.trim()||"Não informado";
function Header({step,setStep,canOpen}:{step:Step;setStep:(s:Step)=>void;canOpen:boolean}){return <header className="topbar"><button className="brand" onClick={()=>setStep(0)} aria-label="Voltar ao início"><img src="/context-agent/assets/nex-logo.png" alt="NEX"/><span>CONTEXT AGENT</span></button><nav aria-label="Etapas do Context Agent">{steps.map((s,i)=><button key={s} disabled={i>1&&!canOpen} aria-current={step===i?"step":undefined} className={step===i?"active":""} onClick={()=>setStep(i as Step)}>{s}</button>)}</nav><span className="counter" aria-label={`Etapa ${step+1} de 6`}>{String(step+1).padStart(2,"0")}/06</span></header>}
function Progress({value}:{value:number}){return <div className="progress"><i style={{width:`${value}%`}}/><b style={{left:`${value}%`}}/></div>}
function Shell({step,setStep,canOpen,progress,children}:{step:Step;setStep:(s:Step)=>void;canOpen:boolean;progress:number;children:React.ReactNode}){const bg=["agent-core.webp","agent-core.webp","company-map.webp","diagnostic.webp","context-master.webp","agent-core.webp"];return <main className={`app step-${step}`} style={{"--scene":`url(/context-agent/assets/${bg[step]})`} as React.CSSProperties}><a className="skip-link" href="#conteudo">Pular para o conteúdo</a><div className="scene" aria-hidden="true"/><div className="beam" aria-hidden="true"/><div className="vignette" aria-hidden="true"/><Header step={step} setStep={setStep} canOpen={canOpen}/><section className="stage" id="conteudo">{children}</section><Progress value={progress}/></main>}
export default function Home(){
 const [step,setStep]=useState<Step>(0),[qi,setQi]=useState(0),[answers,setAnswers]=useState<Answers>({}),[value,setValue]=useState(""),[copied,setCopied]=useState(false),[ready,setReady]=useState(false),[consent,setConsent]=useState(false),[syncState,setSyncState]=useState<"idle"|"syncing"|"saved"|"queued">("idle");
 const complete=questions.every(q=>Boolean(answers[q.id]?.trim()));
 useEffect(()=>{if(!ready)return;if(step===1)window.NEXTracking?.funnelStep("context",questions[qi].id,qi+1,questions.length);else if(step>=2)window.NEXTracking?.funnelDone()},[ready,step,qi]);
 const identifiers=useCallback(()=>{let visitor=window.NEX_TRACK?.visitor||localStorage.getItem("nex_visitor");if(!visitor){visitor=crypto.randomUUID();localStorage.setItem("nex_visitor",visitor)}let session=window.NEX_TRACK?.session||sessionStorage.getItem("nex_session");if(!session){session=crypto.randomUUID();sessionStorage.setItem("nex_session",session)}return {visitor,session}},[]);
 const syncLead=useCallback(async(next:Answers,status:"progress"|"submitted",allowed:boolean)=>{const ids=identifiers();const payload={product:"context-agent",source:"context-agent-web",...ids,name:next.name,company:next.company,status,answers:next,consent:allowed};setSyncState("syncing");try{const response=await fetch("/api/leads",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!response.ok)throw new Error("sync_failed");localStorage.removeItem("nex-context-pending");setSyncState("saved")}catch{localStorage.setItem("nex-context-pending",JSON.stringify(payload));setSyncState("queued")}},[identifiers]);
 useEffect(()=>{try{const raw=localStorage.getItem("nex-context-v1");if(raw){const p=JSON.parse(raw);setAnswers(p.answers||{});setQi(Math.min(questions.length-1,Math.max(0,p.qi||0)));setConsent(Boolean(p.consent));setStep(p.complete?2:0)}}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem("nex-context-v1",JSON.stringify({answers,qi,complete,consent}))},[answers,qi,ready,complete,consent]);
 useEffect(()=>{if(!ready)return;const flush=()=>{try{const raw=localStorage.getItem("nex-context-pending");if(raw){const p=JSON.parse(raw);syncLead(p.answers,p.status,p.consent)}}catch{localStorage.removeItem("nex-context-pending")}};flush();addEventListener("online",flush);return()=>removeEventListener("online",flush)},[ready,syncLead]);
 const score=useMemo(()=>{const option=answers.readiness;const base={strategy:58,marketing:52,sales:55,operation:61,data:42};if(option==="Atrair mais clientes")base.marketing=34;if(option==="Converter melhor")base.sales=35;if(option==="Organizar a operação")base.operation=32;if(option==="Usar melhor dados e tecnologia")base.data=28;const richness=Math.min(15,Object.values(answers).join(" ").length/80);return Object.fromEntries(Object.entries(base).map(([k,v])=>[k,Math.min(88,Math.round(v+richness))]))},[answers]);
 const priority=answers.readiness||"Organizar a operação";
 const diagnosis=priority==="Atrair mais clientes"?"A empresa precisa transformar seu valor em uma mensagem capaz de gerar demanda qualificada.":priority==="Converter melhor"?"O interesse existe, mas o processo comercial ainda não transforma confiança em decisão com consistência.":priority==="Usar melhor dados e tecnologia"?"A empresa opera, mas ainda perde aprendizado porque informações, ferramentas e decisões não estão conectadas.":"A empresa cresceu mais rápido do que seus processos. O próximo salto exige clareza operacional e responsabilidades visíveis.";
 const prompt=useMemo(()=>`CONTEXTO MESTRE DA EMPRESA\n\nVocê é um parceiro estratégico da ${esc(answers.company)}. Use o contexto abaixo como fonte principal antes de recomendar qualquer ação. Não invente informações ausentes; sinalize hipóteses.\n\nResponsável: ${esc(answers.name)}\nSegmento: ${esc(answers.segment)}\nOferta atual: ${esc(answers.offer)}\nCliente mais aderente: ${esc(answers.client)}\nProblema resolvido: ${esc(answers.problem)}\nDiferencial percebido: ${esc(answers.difference)}\nAquisição atual: ${esc(answers.acquisition)}\nProcesso comercial: ${esc(answers.sales)}\nGargalo declarado: ${esc(answers.bottleneck)}\nObjetivo em 12 meses: ${esc(answers.goal)}\nPrioridade escolhida: ${esc(answers.readiness)}\n\nAo responder: 1) conecte a recomendação ao objetivo; 2) priorize ações simples e mensuráveis; 3) diferencie fatos, hipóteses e lacunas; 4) preserve o posicionamento da empresa; 5) proponha o próximo experimento e como medir aprendizado.`,[answers]);
 const saveAnswer=(answer:string)=>{if(!answer.trim())return;const q=questions[qi];const next={...answers,[q.id]:answer.trim()};const done=questions.every(item=>Boolean(next[item.id]?.trim()));setAnswers(next);setValue("");void syncLead(next,done&&consent?"submitted":"progress",consent);window.NEX_TRACK?.send(done?"context_complete":"context_answer",q.id);if(done)setStep(2);else{const nextMissing=questions.findIndex((item,index)=>index>qi&&!next[item.id]);setQi(nextMissing>=0?nextMissing:Math.min(qi+1,questions.length-1))}};
 const submit=()=>saveAnswer(value);
 const editAnswer=(index:number)=>{setQi(index);setValue(answers[questions[index].id]||"");setStep(1)};
 const reset=()=>{localStorage.removeItem("nex-context-v1");localStorage.removeItem("nex-context-pending");setAnswers({});setQi(0);setValue("");setConsent(false);setSyncState("idle");setStep(1)};
 const download=()=>{const blob=new Blob([prompt],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`contexto-mestre-${(answers.company||"empresa").toLowerCase().replace(/[^a-z0-9]+/g,"-")}.txt`;a.click();URL.revokeObjectURL(url)};
 const copy=async()=>{try{await navigator.clipboard.writeText(prompt)}catch{const area=document.createElement("textarea");area.value=prompt;document.body.appendChild(area);area.select();document.execCommand("copy");area.remove()}setCopied(true);window.NEX_TRACK?.send("deliverable_copy","context_master");setTimeout(()=>setCopied(false),1600)};
 const pageProgress=step===1?Math.max(8,Math.round((Object.keys(answers).length/questions.length)*100)):(step/5)*100;
 return <Shell step={step} setStep={setStep} canOpen={complete} progress={pageProgress}>
 {step===0&&<div className="hero layout-left"><div className="eyebrow">NEX CONTEXT AGENT</div><h1>Sua empresa<br/>precisa ser<br/><em>compreendida.</em></h1><p>Converse por alguns minutos e receba um contexto empresarial reutilizável, um diagnóstico inicial e um plano de ação.</p><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Autorizo a NEX a salvar minhas respostas para gerar o diagnóstico e entrar em contato sobre este projeto. Li a <a href="/privacidade" target="_blank" rel="noreferrer">Política de Privacidade</a> e os <a href="/termos" target="_blank" rel="noreferrer">Termos de Uso</a>.</span></label><div className="actions"><button className="primary" disabled={!consent} onClick={()=>setStep(1)}>{Object.keys(answers).length?"Continuar contexto":"Iniciar conversa"}</button>{complete&&<button className="secondary" onClick={()=>setStep(4)}>Abrir entregáveis</button>}</div><div className="glass note"><strong>ISTO JÁ GERA UM RESULTADO UTILIZÁVEL.</strong><span>Suas respostas viram um Contexto Mestre pronto para qualquer IA.</span><small>O progresso fica salvo neste dispositivo e é enviado com segurança à NEX. Você pode recomeçar para apagar a cópia local.</small></div></div>}
 {step===1&&<div className="conversation functional"><div className="glass chat"><div className="question-meta"><div className="eyebrow">PERGUNTA {qi+1} DE {questions.length}</div><button className="text-button" onClick={reset}>Recomeçar</button></div><h2 id="current-question">{questions[qi].q}</h2><p className="hint">{questions[qi].hint}</p><div className="history">{Object.entries(answers).slice(-2).map(([k,v])=><div className="message user" key={k}><small>RESPOSTA SALVA</small><p>{v}</p></div>)}</div>{questions[qi].options?<div className="option-grid" role="group" aria-labelledby="current-question">{questions[qi].options?.map(o=><button key={o} aria-pressed={answers[questions[qi].id]===o} onClick={()=>saveAnswer(o)}>{o}</button>)}</div>:<div className="composer"><label className="sr-only" htmlFor="context-answer">Sua resposta</label><textarea id="context-answer" rows={3} value={value} autoFocus onChange={e=>setValue(e.target.value)} placeholder="Responda do seu jeito…" onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();submit()}}}/><button disabled={!value.trim()} onClick={submit}>Salvar e continuar</button></div>}</div><aside className="glass live"><div className="eyebrow">CONTEXTO AO VIVO</div><div className="live-score"><strong>{Math.round((Object.keys(answers).length/questions.length)*100)}%</strong><span>estruturado</span></div>{[["Empresa",answers.company],["Oferta",answers.offer],["Cliente",answers.client],["Gargalo",answers.bottleneck]].map(a=><div className="fact" key={a[0]}><small>{a[0]}</small><b>{a[1]||"Ainda não respondido"}</b></div>)}<span className="sync-state" role="status" aria-live="polite">{syncState==="syncing"?"Salvando…":syncState==="queued"?"Sem conexão. Salvaremos automaticamente ao reconectar.":syncState==="saved"?"Respostas salvas na NEX.":""}</span></aside></div>}
 {step===2&&<div className="review-layout"><div className="glass map-copy"><div className="eyebrow">REVISÃO · {answers.company}</div><h2>Confira antes de gerar o diagnóstico.</h2><p>As {questions.length} respostas abaixo formam o seu Contexto Mestre.</p><div className="answer-review">{questions.map((q,index)=><button key={q.id} onClick={()=>editAnswer(index)}><small>{String(index+1).padStart(2,"0")} · {q.q}</small><span>{answers[q.id]}</span><b>Editar</b></button>)}</div></div><div className="glass context-score"><small>CONTEXTO CONSTRUÍDO</small><strong>100%</strong><span>As respostas foram organizadas e salvas. Você ainda pode corrigir qualquer item.</span><button className="primary compact" onClick={()=>{void syncLead(answers,"submitted",true);window.NEX_TRACK?.send("diagnosis_generate","context_complete");setStep(3)}}>Gerar diagnóstico</button><button className="text-button" onClick={()=>editAnswer(0)}>Revisar desde o início</button></div></div>}
 {step===3&&<div className="diagnostic-layout"><div className="glass diagnosis"><div className="eyebrow">DIAGNÓSTICO INICIAL · {answers.company}</div><h2>{priority}</h2><p>{diagnosis}</p><div className="lever"><small>OBJETIVO DECLARADO</small><b>{answers.goal}</b></div><button className="primary" onClick={()=>setStep(4)}>Gerar entregáveis</button></div><div className="side-stack"><div className="glass maturity"><div className="eyebrow">LEITURA INICIAL</div>{[["Estratégia",score.strategy],["Marketing",score.marketing],["Vendas",score.sales],["Operação",score.operation],["Dados",score.data]].map(([x,v])=><div className="metric" key={x}><span>{x}</span><i><b style={{width:`${v}%`}}/></i><strong>{v}%</strong></div>)}</div><div className="glass not-now"><small>NÃO FAZER AGORA</small><b>Espalhar esforço em várias frentes antes de validar a prioridade escolhida.</b><span>Este resultado é uma leitura inicial baseada nas respostas, não uma auditoria completa.</span></div></div></div>}
 {step===4&&<div className="deliver-layout"><div className="glass dossier"><div className="eyebrow">CONTEXTO MESTRE · {answers.company}</div><h2>Sua empresa, estruturada para qualquer IA.</h2><p>Copie o prompt completo ou baixe o arquivo. Ele carrega as respostas, o objetivo e as regras para evitar recomendações genéricas.</p><div className="prompt"><small>PRÉVIA DO PROMPT</small><p>{prompt.slice(0,310)}…</p></div><div className="actions"><button className="primary" onClick={copy}>{copied?"Prompt copiado":"Copiar prompt"}</button><button className="secondary" onClick={()=>{download();window.NEX_TRACK?.send("deliverable_download","context_master")}}>Baixar arquivo</button></div></div><div className="glass use-cases"><small>PRONTO PARA USAR EM</small><b>Marketing · Vendas · Processos</b><b>Contratações · IA · Decisões</b><span>Gerado com as respostas de {answers.name}.</span><button className="primary compact" onClick={()=>setStep(5)}>Criar plano inicial</button></div></div>}
 {step===5&&<div className="plan glass"><div className="eyebrow">PRIMEIRO CICLO · 30 DIAS</div><h2>Agora existe um próximo passo.</h2><p>Um ciclo inicial baseado na prioridade “{priority.toLowerCase()}”.</p><div className="plan-grid"><article className="active"><small>01 · CLAREZA</small><b>Definir a mudança central</b><span>Transformar “{answers.bottleneck}” em uma hipótese que possa ser testada.</span></article><article><small>02 · EXECUÇÃO</small><b>Rodar um experimento</b><span>Criar uma ação pequena ligada ao objetivo: {answers.goal}</span></article><article><small>03 · APRENDIZADO</small><b>Registrar o que aconteceu</b><span>Medir resposta, decisão e próximo ajuste antes de ampliar investimento.</span></article></div><div className="final"><div><small>SEU CONTEXTO CONTINUA VIVO</small><b>Volte, atualize as respostas e gere uma nova versão quando a empresa mudar.</b></div><div className="actions"><button className="secondary" onClick={()=>editAnswer(0)}>Atualizar contexto</button><a className="primary" href={`https://wa.me/${(typeof window!=="undefined"&&window.NEX_WHATSAPP_NUMBER)||"5511953878155"}?text=${encodeURIComponent(`Oi, concluí meu Contexto NEX da empresa ${answers.company} e quero conversar sobre o diagnóstico.`)}`} target="_blank" rel="noreferrer" onClick={()=>window.NEX_TRACK?.send("whatsapp","context_analysis")}>Agendar análise</a></div></div></div>}
 </Shell>
}
