import {storage,user,sameOrigin,unavailable,isAdmin,sessionCookie} from '@/studio/lib/storage';
import {questions,visibleQuestions,type Answers} from '@/studio/lib/briefing';
export async function GET(request:Request){let owner=(await user(request));let cookie='';if(!owner){owner=crypto.randomUUID();cookie=sessionCookie(owner)}const headers:Record<string,string>={'Cache-Control':'private, no-store'};if(cookie)headers['Set-Cookie']=cookie;try{const {db}=storage();const row=await db.prepare('SELECT * FROM projects WHERE owner=? ORDER BY updated DESC LIMIT 1').bind(owner).first<{id:string;answers:string;cursor:number;status:string}>();if(!row)return Response.json({project:null,files:[],admin:(await isAdmin(request))},{headers});const f=await db.prepare('SELECT id,name,mime,size FROM files WHERE project=?').bind(row.id).all();const operation=await db.prepare('SELECT stage,message,preview,meeting,paid_at,agreed_amount,materials_ready,due,updated FROM project_operations WHERE project=?').bind(row.id).first();const events=await db.prepare('SELECT kind,message,created FROM project_events WHERE project=? ORDER BY created DESC LIMIT 30').bind(row.id).all();return Response.json({project:{...row,answers:JSON.parse(row.answers)},files:f.results,operation,events:events.results,admin:(await isAdmin(request))},{headers});}catch(e){return unavailable(e)}}
export async function POST(request:Request){const owner=(await user(request));if(!owner)return Response.json({error:'Acesso não autorizado.'},{status:401});if(!sameOrigin(request))return Response.json({error:'Origem inválida.'},{status:403});if(Number(request.headers.get('content-length')||0)>160000)return Response.json({error:'Briefing excede o limite.'},{status:413});let body:{id?:string|null;answers?:Record<string,unknown>;cursor?:number;action?:string;consent?:boolean};try{body=await request.json();}catch{return Response.json({error:'Briefing inválido.'},{status:400})}
if(!body||typeof body!=='object'||(body.id!=null&&typeof body.id!=='string')||!body.answers||typeof body.answers!=='object'||Array.isArray(body.answers)||body.action&&!['save','submit'].includes(body.action))return Response.json({error:'Briefing inválido.'},{status:400});
const a:Answers={};for(const q of questions){const v=body.answers[q.id];if(v!==undefined){if(typeof v!=='string'||v.length>6000||q.options&&v&&!q.options.includes(v))return Response.json({error:'Confira as respostas do briefing.'},{status:400});a[q.id]=v.trim()}}
if(a.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(a.email))return Response.json({error:'Informe um e-mail válido.'},{status:400});const submit=body.action==='submit';if(submit){if(body.consent!==true)return Response.json({error:'Confirme o envio do briefing para análise.'},{status:400});const missing=visibleQuestions(a).find(q=>q.required&&!a[q.id]);if(missing)return Response.json({error:'Complete: '+missing.title},{status:400});}
const cursor=typeof body.cursor==='number'&&Number.isInteger(body.cursor)?Math.max(0,Math.min(body.cursor,30)):0;
try{const {db}=storage();let id=body.id;const now=new Date().toISOString();if(id){const found=await db.prepare('SELECT id,status FROM projects WHERE id=? AND owner=?').bind(id,owner).first<{id:string;status:string}>();if(!found)return Response.json({error:'Projeto não encontrado.'},{status:404});if(found.status==='submitted')return Response.json({error:'O briefing já foi enviado. Peça uma revisão à NEX pelo painel.'},{status:409});await db.prepare('UPDATE projects SET answers=?,cursor=?,updated=? WHERE id=? AND owner=?').bind(JSON.stringify(a),cursor,now,id,owner).run();}else{id=crypto.randomUUID();await db.prepare('INSERT INTO projects(id,owner,answers,cursor,status,updated) VALUES(?,?,?,?,?,?)').bind(id,owner,JSON.stringify(a),cursor,'draft',now).run();}
if(submit){await db.batch([db.prepare('INSERT INTO project_operations(project,updated) VALUES(?,?) ON CONFLICT(project) DO NOTHING').bind(id,now),db.prepare('INSERT INTO project_events(id,project,actor,kind,message,created) SELECT ?,id,?,\'submitted\',\'Briefing enviado para análise da NEX.\',? FROM projects WHERE id=? AND status<>\'submitted\'').bind(crypto.randomUUID(),owner,now,id),db.prepare('UPDATE projects SET status=\'submitted\',updated=? WHERE id=? AND owner=?').bind(now,id,owner)]);}
return Response.json({id,status:submit?'submitted':'draft'});}catch(e){return unavailable(e)}}
